export const lectureCategories = [
  { id: 'tafsir', name: 'التفسير', letter: 'ت', count: 29 },
  { id: 'fiqh', name: 'الفقه', letter: 'ف', count: 65 },
  { id: 'aqeedah', name: 'العقيدة', letter: 'ع', count: 42 },
  { id: 'hadith', name: 'الحديث', letter: 'ح', count: 38 },
  { id: 'seerah', name: 'السيرة', letter: 'س', count: 21 },
  { id: 'raqaiq', name: 'الرقائق', letter: 'ر', count: 18 },
  { id: 'quran_sciences', name: 'علوم قرآن', letter: 'ق', count: 12 },
  { id: 'hadith_term', name: 'مصطلح حديث', letter: 'م', count: 15 },
  { id: 'usul_fiqh', name: 'أصول فقه', letter: 'أ', count: 24 },
  { id: 'adab', name: 'آداب طالب العلم', letter: 'آ', count: 8 },
  { id: 'ilal', name: 'علل الحديث', letter: 'ع', count: 11 },
  { id: 'jarh', name: 'جرح وتعديل', letter: 'ج', count: 7 },
  { id: 'takhreej', name: 'التخريج', letter: 'خ', count: 9 },
  { id: 'qawaid', name: 'قواعد فقهية', letter: 'ق', count: 14 },
  { id: 'lugha', name: 'اللغة العربية', letter: 'ل', count: 17 },
  { id: 'general', name: 'دروس عامة', letter: 'د', count: 33 },
  { id: 'fawaid', name: 'فوائد', letter: 'ف', count: 50 },
];
