// كتالوج قوائم تشغيل قناة "أصحاب الحديث" (youtube.com/@ashabelhadeth) مصنّفة على
// التصنيفات العلمية الموجودة فعلياً في الموقع. يُستخدم بواسطة importYoutubeCatalog.js.
export const PLAYLIST_CATALOG = [
  { id: 'PLZiXoKUMZB0Y', series: 'منهج السالكين وتوضيح الفقه في الدين', category: 'الفقه' },
  { id: 'PLdHa0Mf_E84U', series: 'القواعد المثلى في صفات الله وأسمائه الحسنى', category: 'العقيدة' },
  { id: 'PLcFpGrV9TPOM', series: 'غاية السول في سيرة الرسول', category: 'السيرة' },
  { id: 'PLHkZDDJnZveg', series: 'الحث على طلب العلم', category: 'آداب طالب العلم' },
  { id: 'PLZoj-x4tOZRw', series: 'مختصر البخاري لابن أبي جمرة', category: 'الحديث' },
  { id: 'PLcRKbfHyW_FI', series: 'رسالة لطيفة في أصول الفقه', category: 'أصول فقه' },
  { id: 'PLzgycZElueFgKsu7uNTl1mJpcuTYwlQGz', series: 'الأجوبة الجلية', category: 'العقيدة' },
  { id: 'PLzgycZElueFhacG0iTCqBn5M9w8m4cIF9', series: 'الدرة المضية (السفارينية)', category: 'العقيدة' },
  { id: 'PLzgycZElueFiqN1mBkxn99Ci4tDJ_ke6V', series: 'أيها الولد - الغزالي', category: 'آداب طالب العلم' },
  { id: 'PLzgycZElueFjzOR78vlk-Qk4Gark1tQ2y', series: 'الأرجوزة الميئية', category: 'الفقه' },
  { id: 'PLzgycZElueFiH5qxR0tXSi7ngO-ZPJOEo', series: 'تذكرة السامع والمتكلم في آداب العالم والمتعلم', category: 'آداب طالب العلم' },
  { id: 'PLzgycZElueFiv-sooSxuj-AnKbFHc-L60', series: 'ألفية العراقي في علوم الحديث', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFg-1urBM7l07MiI-5ucM9Xq', series: 'رسالة الأخلاق للإيجي', category: 'الرقائق' },
  { id: 'PLzgycZElueFhcCIN7-PoS1p8wIll1x72e', series: 'دروس ومحاضرات مجمع أحمد بن حنبل', category: 'دروس عامة', featured: true },
  { id: 'PLzgycZElueFhPEmzILz8s4Vp1CKf60y7E', series: 'أصول السنة لابن أبي زمنين', category: 'العقيدة' },
  { id: 'PLzgycZElueFhqvJAXZCnByu3e_oFXiE9s', series: 'الإيمان لأبي عبيد القاسم بن سلام', category: 'العقيدة' },
  { id: 'PLzgycZElueFgUJByxQIuhlY4uPK-pIO3i', series: 'القدر لابن وهب', category: 'العقيدة' },
  { id: 'PLzgycZElueFjyn_Q3i6H7esK58KAjAYuF', series: 'كتابا النزول والصفات للدارقطني', category: 'العقيدة' },
  { id: 'PLzgycZElueFjy1Hf94qNA61KzlQM0gSiJ', series: 'عقيدة السلف أصحاب الحديث لأبي عثمان الصابوني', category: 'العقيدة' },
  { id: 'PLzgycZElueFhFBj9SPpocDlzG_UkqboLU', series: 'الدالية لأبي الخطاب الكلوذاني', category: 'العقيدة' },
  { id: 'PLzgycZElueFjdeD0O1Y1AhO18Da-6KkOy', series: 'المدخل إلى دراسة علم البلاغة', category: 'اللغة العربية' },
  { id: 'PLzgycZElueFgKu8P02Qvui9i3ViCAj0fS', series: 'نظم الجوهر المكنون في البلاغة', category: 'اللغة العربية' },
  { id: 'PLzgycZElueFjdw_B4bi8ATnRmG9-PrBM9', series: 'حلية طالب العلم', category: 'آداب طالب العلم' },
  { id: 'PLzgycZElueFjuRZQTNZBFISShekJDqLyD', series: 'شفاء الصدور في زيارة القبور للشيخ مرعي', category: 'العقيدة' },
  { id: 'PLzgycZElueFjk16ckfCum2CI69So5pA76', series: 'الحائية لابن أبي داود - الدالية لأبي الخطاب', category: 'العقيدة' },
  { id: 'PLzgycZElueFj4qxvbV3v56nu90AphskhB', series: 'كتاب الاعتقاد لابن أبي يعلى', category: 'العقيدة' },
  { id: 'PLzgycZElueFhYjiIW1MNAWASEiPd6Naxx', series: 'أخصر المختصرات', category: 'الفقه' },
  { id: 'PLzgycZElueFjEi_wdWoEYhU0_qBlSCXTB', series: 'سنن أبي داود', category: 'الحديث' },
  { id: 'PLzgycZElueFgH7BKrVObGBM2Pe968ZaBQ', series: 'الورقات في أصول الفقه', category: 'أصول فقه' },
  { id: 'PLzgycZElueFjC3Azegq-GU6ZmgylSJJ2-', series: 'منظومة القواعد الفقهية لابن سند', category: 'قواعد فقهية' },
  { id: 'PLzgycZElueFgzSHmQ9BLy6_dK1aSQJKLl', series: 'فروع الفقه لابن المبرد', category: 'الفقه' },
  { id: 'PLzgycZElueFhNd8IxAGm6bfwh35ojK8N6', series: 'التعريف بالفرق المنتسبة للإسلام', category: 'العقيدة' },
  { id: 'PLzgycZElueFjqLhsQB6u2hGTG81izvdxj', series: 'بداية العابد وكفاية الزاهد في فقه الإمام أحمد', category: 'الفقه' },
  { id: 'PLzgycZElueFhAe9KYt8OvLErtfWkCYIf8', series: 'المدخل التعريفي بالمذاهب الأربعة', category: 'الفقه' },
  { id: 'PLzgycZElueFizQo77zQhfGJBcIk4cDe4a', series: 'دورة مفسر', category: 'علوم قرآن' },
  { id: 'PLzgycZElueFiuPeiasYHqf0YJC4aH7pdT', series: 'العقيدة الطحاوية', category: 'العقيدة' },
  { id: 'PLzgycZElueFgcIH80BO7ITlvnnLIGJqL5', series: 'المأمول من شرح سلم الوصول', category: 'أصول فقه' },
  { id: 'PLzgycZElueFhVeumWQEL_1g2kxx0OPo-7', series: 'نجاة الخلف في اعتقاد السلف لعثمان النجدي', category: 'العقيدة' },
  { id: 'PLzgycZElueFhr3-jnYpfyDTvZPzaWFjmG', series: 'الموطأ', category: 'الحديث' },
  { id: 'PLzgycZElueFj79fLqQCwkiizPYkAcmUbv', series: 'التعليق الممجد على منظومة محمد في الجرح والتعديل', category: 'جرح وتعديل' },
  { id: 'PLzgycZElueFiFzqszy-_ySyP4PGCWxLW5', series: 'منظومة الزمزمي في علوم القرآن', category: 'علوم قرآن' },
  { id: 'PLzgycZElueFh2RVP6hplVkaYHRDe28faw', series: 'فتح الكريم المنان في آداب حملة القرآن', category: 'علوم قرآن' },
  { id: 'PLzgycZElueFgtZLxk0Ucxm__y0Cx86CVV', series: 'تفسير المشكل من غريب القرآن لمكي بن أبي طالب', category: 'علوم قرآن' },
  { id: 'PLzgycZElueFiD10AhKy2I_iGDeqEzHcKZ', series: 'التفسير الوسيط للواحدي', category: 'التفسير' },
  { id: 'PLzgycZElueFjzoqyqhi9sTEXdQoqsaLTg', series: 'كتب الإمام محمد بن عبد الوهاب', category: 'العقيدة' },
  { id: 'PLzgycZElueFivTCXEbnBaG9kpoZ1BzyWT', series: 'جامع الترمذي (مقرأة السنة)', category: 'الحديث' },
  { id: 'PLzgycZElueFhpOlcpv4v9Pm3J2A81sIj3', series: 'إعانة الكرام على ختم بلوغ المرام', category: 'الحديث' },
  { id: 'PLzgycZElueFjniRjM4m1e7-isvmtTBOMp', series: 'صحيح مسلم (مقرأة السنة)', category: 'الحديث' },
  { id: 'PLzgycZElueFjwt8HG8Bu2ofJj3gu1Yrwh', series: 'الروض المربع شرح زاد المستقنع', category: 'الفقه' },
  { id: 'PLzgycZElueFjcVSLWl__uWT-9iQbA2-Ke', series: 'صحيح البخاري (مقرأة السنة)', category: 'الحديث' },
  { id: 'PLzgycZElueFhYBDn_zHfaheJ2auAgr-TQ', series: 'غاية السول في علم الأصول', category: 'أصول فقه' },
  { id: 'PLzgycZElueFgtEhp9ECTIHgYVk-YgCanL', series: 'شرح ألفية العلل', category: 'علل الحديث' },
  { id: 'PLzgycZElueFhulfT3_Nc50B8Mxvu_AO_W', series: 'تجريد كتب شيخ الإسلام ابن تيمية', category: 'العقيدة' },
  { id: 'PLzgycZElueFh439VjlJuEc1N_tlfivXl3', series: 'كتب العقيدة المسندة', category: 'العقيدة' },
  { id: 'PLzgycZElueFgW2mQqL0SY8RtyUZu1g0bR', series: 'نظم مئة المعاني في علم البلاغة', category: 'اللغة العربية' },
  { id: 'PLzgycZElueFjjxXYtJG6oP4aYgO_gGZmL', series: 'كتاب المنجيات على الواجبات المتحتمات', category: 'الرقائق' },
  { id: 'PLzgycZElueFh_9CEZhqR9NdOKW7nfMX8p', series: 'تفسير الجلالين', category: 'التفسير' },
  { id: 'PLzgycZElueFhs-q27MIm_JeJOHJgdnWx0', series: 'سنن ابن ماجه', category: 'الحديث' },
  { id: 'PLzgycZElueFhu4UDzd3PjQZb0Itvk8YDr', series: 'السنن الكبير للبيهقي', category: 'الحديث' },
  { id: 'PLzgycZElueFhDW68AW_jRUgQG0Q4Mxzio', series: 'العلل الكبير للترمذي', category: 'علل الحديث' },
  { id: 'PLzgycZElueFgD1PkbeesHEYs-pDkf4ZcC', series: 'المبدع شرح المقنع', category: 'الفقه' },
  { id: 'PLzgycZElueFgicMD0Zs-f2_w88kqNPXms', series: 'فتح الباري لابن حجر', category: 'الحديث' },
  { id: 'PLzgycZElueFgS1CCtALh8eaaAH2padpmx', series: 'منازل السائرين للهروي', category: 'الرقائق' },
  { id: 'PLzgycZElueFjlzSk0VCU0bsvoaGbDHK4t', series: 'شرح السنة للبربهاري', category: 'العقيدة' },
  { id: 'PLzgycZElueFgKBm8Z5AUbv5J8Bpkb_-JT', series: 'شروح كتب الحنابلة في العقيدة', category: 'العقيدة' },
  { id: 'PLzgycZElueFhQwSqZCmGqEleKOMH7T5bV', series: 'الفوائد المنتقاة', category: 'فوائد' },
  { id: 'PLzgycZElueFihmEmGKD7tvjn2gn1YkdzH', series: 'سير أعلام العباد', category: 'السيرة' },
  { id: 'PLzgycZElueFhlRSAIxC6oSqpVnNbQRNm6', series: 'التفسير الوجيز للواحدي', category: 'التفسير' },
  { id: 'PLzgycZElueFjs8fWzpLUHr7j3E99ZiRBw', series: 'الشرح والتتميم للرفع والتكميل في الجرح والتعديل', category: 'جرح وتعديل' },
  { id: 'PLzgycZElueFgFAWLWNwVvIsN8FUTrZoaM', series: 'ألفية السيوطي', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFhegImtIrOvKux6oO2YnZR7', series: 'قواعد ابن رجب', category: 'قواعد فقهية' },
  { id: 'PLzgycZElueFjiF5U0s_Z2hElu0s4-F3aD', series: 'تجريد كتاب الكافي لابن قدامة', category: 'الفقه' },
  { id: 'PLzgycZElueFgAczMaFRaeuon9hNXjKpau', series: 'المدخل إلى علم العلل', category: 'علل الحديث' },
  { id: 'PLzgycZElueFhPA3xYydXIdiV50vs6fW88', series: 'تجريد كتاب المقنع لابن قدامة', category: 'الفقه' },
  { id: 'PLzgycZElueFiH7yMvgC9oArUFHn_Sp0cw', series: 'تجريد كتاب عمدة الفقه لابن قدامة', category: 'الفقه' },
  { id: 'PLzgycZElueFjCgb4bc2HIKtkleAhR2n99', series: 'مقدمة أصول التفسير لابن تيمية', category: 'علوم قرآن' },
  { id: 'PLzgycZElueFjLpQv5meOEnPrfNjgf2Ebo', series: 'ختم عمدة الأحكام', category: 'الحديث' },
  { id: 'PLzgycZElueFhrDoB9WekxzgkYTsecwNXr', series: 'تدريب الراوي للسيوطي', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFgsORfwbK2WrV6CTnxzRGsA', series: 'نخبة الفكر لابن حجر', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFiMqGTmi7tYxzoWDmFbpnVK', series: 'الباعث الحثيث لابن كثير', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFiPSSB9XOQIKU368IqZf881', series: 'الأقوال المرضية على المنظومة البيقونية', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFiSNwHed-Tm2W9_dVxuXvfm', series: 'تهذيب أوضح العبارات في شرح المحلي على الورقات', category: 'أصول فقه' },
  { id: 'PLzgycZElueFjPuS870DX0DmZj-gV-Q4GV', series: 'منظومة المدلسين للإتيوبي', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFghRtIFPgQsCDsIicmXeCe-', series: 'سنن النسائي', category: 'الحديث' },
  { id: 'PLzgycZElueFhEVgL3s-0SbY9C9xlLssK6', series: 'منهاج العابدين', category: 'الرقائق' },
  { id: 'PLzgycZElueFiC6XZnabUxSzorn-JoVoD3', series: 'مقتطفات وفوائد من الدروس', category: 'فوائد' },
  { id: 'PLzgycZElueFiUoIxjkspY9eqYolOqighs', series: 'الشرح المكثف للعقيدة الواسطية', category: 'العقيدة' },
  { id: 'PLzgycZElueFglM6ncYCFuA3QDVD65lD6x', series: 'كتاب التمييز للإمام مسلم', category: 'مصطلح حديث' },
  { id: 'PLzgycZElueFjOFj9zDdIX0-VSGzof5lre', series: 'دروس متنوعة', category: 'دروس عامة' },
  { id: 'PLzgycZElueFjiC07duzR2gpVC6rSekq5B', series: 'مسائل الجاهلية - فضل الإسلام - كشف الشبهات', category: 'العقيدة' },
  { id: 'PLzgycZElueFiZZFqFbY3_yqA7fcxemwBb', series: 'اللامية لابن تيمية', category: 'العقيدة' },
  { id: 'PLzgycZElueFgGreUlm6YIthCqsXWFQx0k', series: 'الجامع لعبادة الله - القواعد الأربعة - الأصول الستة - كلمة التوحيد', category: 'العقيدة' },
  { id: 'PLzgycZElueFhXfsanOzolpP64jGTTOvQC', series: 'الفتوى الحموية لابن تيمية', category: 'العقيدة' },
  { id: 'PLzgycZElueFixm7F6lbiXjHeW6sIZ1IL-', series: 'الرسالة التدمرية لابن تيمية', category: 'العقيدة' },
  { id: 'PLzgycZElueFicIKbQK_ZepjmqHZVIRnZw', series: 'معنى الطاغوت - رسالة إلى أهل القصيم', category: 'العقيدة' },
  { id: 'PLzgycZElueFiXwQwPLO8Nbn0RDPh69N3C', series: 'كتاب التوحيد', category: 'العقيدة' },
  { id: 'PLzgycZElueFjUjKiXpjSxNC-CIf_yUhf1', series: 'ثلاثة الأصول - نواقض الإسلام', category: 'العقيدة' },
];
